[[plugin]]
id           = "aabidk20/noctalia-ytmusic"
name         = "Noctalia YT Music"
version      = "0.2.1"
author       = "Aabid"
license      = "MIT"
icon         = "music"
description  = "YouTube Music client for Noctalia v5 - miniplayer & full view"
deprecated   = false
plugin_api   = 23
tags         = ["music", "media"]
dependencies = ["yt-dlp", "mpv", "mpv-mpris", "jq", "curl", "nc"]