[[plugin]]
id           = "aabidk20/yt-music"
name         = "YouTube Music"
version      = "0.2.4"
author       = "Aabid"
license      = "MIT"
icon         = "brand-youtube-filled"
description  = "YouTube Music client for Noctalia v5 - miniplayer & full view"
deprecated   = false
plugin_api   = 23
tags         = ["music", "media"]
dependencies = ["yt-dlp", "mpv", "mpv-mpris", "jq", "curl", "nc"]